steps:
  - name: 'gcr.io/trans-proposal-206815/github.com/harshavardhanj/docker_files:af2d28f'
    args:
      - 'build'
      - '--platform'
      - 'linux/arm,linux/arm64,linux/amd64'
      - '-f'
      - 'endlessh-Dockerfile'
