steps:
  # Get the Docker Hub user ID from Secrets Manager and save it to a file
  - name: 'gcr.io/cloud-builders/gcloud'
    #    entrypoint: "bash"
    args: ["gcloud", "beta", "secrets", "versions", "access", "1", "--secret=DockerHubUserID", ">", "./UserID"]

  # Get the Docker Hub access token from Secrets Manager and save it to a file
  - name: 'gcr.io/cloud-builders/gcloud'
    #entrypoint: "bash"
    args: ["gcloud", "beta", "secrets", "versions", "access", "1", "--secret=DockerHubAccessToken", ">", "./AccessToken"]

  # Log in to Docker Hub using the credentials obtained in the previous steps
  - name: 'gcr.io/cloud-builders/docker'
    args: ["login", "-u", "$(cat ./UserID)", "-p", "$(cat ./AccessToken)"]

  # Build the container image using `buildx` and push it to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'harshavardhanj/docker-buildx:latest'
      - '--platform'
      - 'linux/amd64,linux/arm64,linux/s390x,linux/386,linux/arm/v7,linux/arm/v6'
      - '-f'
      - './docker-cloud-builder/Dockerfile'
      - '--push'
      - './docker-cloud-builder/.'
