steps:
  - name: 'gcr.io/trans-proposal-206815/github.com/harshavardhanj/docker_files:18e2c9b'
    args:
      - 'build'
      - '-f'
      - './docker-cloud-builder/endlessh-Dockerfile'
      - '--load'
      - './docker-cloud-builder/.'
