steps:
  - name: 'gcr.io/trans-proposal-206815/github.com/harshavardhanj/docker_files:e15a133'
    args:
      - 'docker-buildx'
      - 'build'
      - '-t'
      - 'gcr.io/trans-proposal-206815/github.com/harshavardhanj/endlessh'
      - '--platform'
      - 'linux/arm,linux/arm64,linux/amd64'
      - '-f'
      - 'endlessh-Dockerfile'
