steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/github.com/docker_files/docker-buildx:$SHORT_SHA'
      - '-f'
      - './docker-cloud-builder/Dockerfile'
images: ['gcr.io/$PROJECT_ID/github.com/docker_files/docker-buildx:$SHORT_SHA']
