# Config file to be used by Container Structure Test
# for docker-buildx:latest image

schemaVersion: 2.0.0

metadataTest:
  labels:
    - key: 'maintainer'
      value: 'Harsha Vardhan J'
    - key: 'github.account'
      value: 'https://github.com/HarshaVardhanJ'
    - key: 'dockerfile.github.page'
      value: 'https://github.com/HarshaVardhanJ/docker_files/blob/non-root/docker-cloud-builder/Dockerfile'
  workdir: "/"
  entrypoint: ["entrypoint.sh"]
  cmd: []

commandTests:
  - name: "Check if 'docker' is installed in PATH"
    command: "command"
    args: ["-v", "docker"]
    expectedOutput: [".*docker"]
    exitCode: 0

  - name: "Check if 'docker-buildx' is installed in PATH"
    command: "command"
    args: ["-v", "docker-buildx"]
    expectedOutput: [".*docker-buildx"]
    exitCode: 0

  - name: "Check if running as 'root' user"
    command: "whoami"
    expectedOutput: ["root"]
    exitCode: 0

  - name: "Check if non-root user 'docker' exists"
    command: "id"
    args: ["-u", "docker"]
    expectedOutput: ["1000"]
    exitCode: 0

  - name: "Check buildx builder status"
    setup: [["entrypoint.sh", "inspect"]]
    command: "su-exec"
    args: ["docker", "docker-buildx", "inspect"]
    expectedOutput: ["Name:   multiarch-builder", "Driver: docker-container", "Status:    running"]
    excludedOutput: ["Error:.*"]

  - name: "Check if /home/docker/.docker/config.json exists"
    setup: [["entrypoint.sh", "version"]]
    command: "ls"
    args: ["/home/docker/.docker/config.json"]
    exitCode: 0

fileExistenceTests:
  - name: "Check if 'docker-buildx' is executable"
    path: "/usr/bin/docker-buildx"
    shouldExist: true
    isExecutableBy: 'any'

  - name: "Check if entrypoint.sh script is executable"
    path: "/usr/bin/entrypoint.sh"
    shouldExist: true
    isExecutableBy: 'any'
