# First Docker compose file
#
# Scope         :   Build a Drupal content management site
#
# Requirements  :   * Install the Drupal image. It also needs a DB.
#                   * Install Postgres as the backend DB.
#                   * Open port 8080 to the port exposed by Drupal.
#                   * Set POSTGRES_PASSWORD for Postgres container.
#                   * Open http://localhost:8080 on web browser to configure Drupal.
#                   * In the web-based setup, will need to point to the DB whose name
#                   is the service name of the DB container.
#                   * If possible, use volumes to store Drupal data.
#
version: "3"


services:

    drupal:
        image: drupal:fpm-alpine
        ports:
            - "8080:9000"
        volumes:
            - drupal-data1:/var/www/html/modules
            - drupal-data2:/var/www/html/profiles
            - drupal-data3:/var/www/html/themes
            - drupal-data4:/var/www/html/sites
        depends_on:
            - psql
        restart: always

    psql:
        image: postgres:alpine
        ports:
            - "5432"
        volumes:
            - psql-db:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=password
        restart: always


volumes:
    psql-db:
        driver: local
    drupal-data1:
        driver: local
    drupal-data2:
        driver: local
    drupal-data3:
        driver: local
    drupal-data4:
        driver: local
