# Config file to be used by Container Structure Test
# for openssh:alpine image


schemaVersion: 2.0.0

metadataTest:
  labels:
    - key: 'maintainer'
      value: 'Harsha Vardhan J'
    - key: 'github.account'
      value: 'https://github.com/HarshaVardhanJ'
    - key: 'dockerfile.github.page'
      value: 'https://github.com/HarshaVardhanJ/docker_files/blob/master/openssh/openssh-alpine/Dockerfile'
  entrypoint: ["/usr/local/bin/entrypoint.sh"]
  cmd: ["ssh"]
  exposedPorts: ["22"]

globalEnvVars:
  - key: "USER"
    value: "test"
  - key: "PASSWORD"
    value: "testpwd"
  - key: "SSH_PUBKEY"
    value: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMYv/mA/ZusCbM8EgMZ4Wq5mm14ewq4CoCDr2xu7YgHB Test SSH Key used for testing purposes"

commandTests:
  - name: "Check user id"
    setup: [["/usr/local/bin/entrypoint.sh"]]
    command: "id"
    args: ["-u", "${USER}"]
    expectedOutput: ["1000"]
    exitCode: 0

  - name: "Check if 'authorized_keys' file exists"
    setup: [["/usr/local/bin/entrypoint.sh"]]
    command: "ls"
    args: ["/home/${USER}/.ssh/authorized_keys"]
    expectedOutput: [".*authorized_keys.*"]
    exitCode: 0

fileExistenceTests:
  - name: "Check if 'sshd_config' exists"
    path: "/etc/ssh/sshd_config"
    shouldExist: true
    permissions: '-rw-r--r--'
    uid: 0
    gid: 0

