version: "3.5"
services:
    openssh:
        image: harshavardhanj/openssh
        ports:
            - "2222:22"
        secrets:
            - ssh_user
            - ssh_password
            - ssh_pubkey
        environment:
            - USER_FILE=ssh_user
            - PASSWORD_FILE=ssh_password
            - SSH_PUBKEY_FILE=ssh_pubkey
        deploy:
            mode: replicated
            replicas: 3
            placement:
                constraints:
                    - node.role == worker
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s
secrets:
    ssh_user:
        external: true
    ssh_password:
        external: true
    ssh_pubkey:
        external: true
