# Config file to be used by Container Structure Test
# for endlessh:latest image

schemaVersion: 2.0.0

metadataTest:
  labels:
    - key: 'maintainer'
      value: 'Harsha Vardhan J'
    - key: 'github.account'
      value: 'https://github.com/HarshaVardhanJ'
    - key: 'dockerfile.github.page'
      value: 'https://github.com/HarshaVardhanJ/docker_files/blob/master/endlessh/Dockerfile'
    - key: 'software.author.github.page'
      value: 'https://github.com/skeeto/endlessh'
    - key: 'software.release.version'
      value: '1.0'
  exposedPorts: ["2222"]
  entrypoint: ["/endlessh"]
  cmd: ["-v"]

fileExistenceTests:
  - name: 'Endlessh executable'
    path: '/endlessh'
    shouldExist: true
    isExecutableBy: 'any'
    permissions: '-rwxr-xr-x'
