# docker-compose.yaml file for Gitea
#
version: "3.7"
services:
  gitea:
    image: harshavardhanj/gitea:1.11.0
    restart: always
    environment:
      USER_UID: 1000
      USER_GID: 1000
    ports:
      - "8080:3000"
      - "2222:22"
    volumes:
      - type: volume
        source: gitea
        target: /data
volumes:
  gitea:
