steps:
  # Get the Docker Hub user ID from Secrets Manager and save it to a file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: "bash"
    args: ["./nginx/getCredentials.sh"]

  # Log in to Docker Hub using the credentials obtained in the previous steps
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: "bash"
    args: ["-c", "docker login --username=$(cat ./UserID) --password=$(cat ./AccessToken)"]

    # Pull buildx image from Docker Hub and build 'nginx-brotli-modsec:latest' image with multi-arch support
  - name: 'harshavardhanj/docker-buildx:latest'
    args:
      - 'build'
      - '-t'
      - 'harshavardhanj/nginx-brotli-modsec:latest'
      - '--platform'
      - 'linux/amd64,linux/arm64,linux/386,linux/arm/v7,linux/arm/v6'
      - '-f'
      - './nginx/nginx-brotli-modsecurity-alpine/Dockerfile'
      - '--push'
      - './nginx/nginx-brotli-modsecurity-alpine/.'

timeout: "5400s"
options:
  machineType: 'N1_HIGHCPU_8'
