steps:
  # Get the Docker Hub user ID from Secrets Manager and save it to a file
  - name: 'gcr.io/cloud-builders/gcloud'
    id: "getCredentials"
    waitFor: ["-"]
    entrypoint: 'bash'
    args: ["./docker-cloud-builder/getCredentials.sh"]

  # Log in to Docker Hub using the credentials obtained in the previous steps
  - name: 'gcr.io/cloud-builders/docker'
    id: "dockerLogin"
    waitFor: ["getCredentials"]
    entrypoint: 'bash'
    args: ["-c", "docker login --username=$(cat ./UserID) --password=$(cat ./AccessToken)"]

  # Get build arguments
  #  - name: 'alpine'
  #    id: "getEnv"
  #    waitFor: ["-"]
  #    #args: ['sh', '-c', 'date --utc +"%Y-%m-%dT%H:%M:%SZ" > ./_DATE_TIME']
  #    args: ['sh', '-c', 'cat ./VERSION" > ./_DATE_TIME']

  # Build from Dockerfile using the docker-buildx:stable image, and
  # tag the image with 'untested' and push to Docker Hub
  - name: 'harshavardhanj/docker-buildx:stable'
    id: "dockerBuildPush"
    waitFor: ["getCredentials", "dockerLogin"]
    entrypoint: 'sh'
    #args: ["-c", "/usr/bin/entrypoint.sh build --build-arg BUILD_DATE=$(date --utc +%Y-%m-%dT%H:%M:%SZ)"]
    args:
      - '-c'
      - '/usr/bin/entrypoint.sh'
      - 'build'
      - '--build-arg'
      - 'BUILD_DATE=$(date --utc +%Y-%m-%dT%H:%M:%SZ)'
      - '--build-arg'
      - 'VCS_REF=$SHORT_SHA'
      - '-t'
      - 'harshavardhanj/binfmt:untested'
      - '-f'
      - './binfmt/Dockerfile'
      - '--push'
      - './binfmt/.'

  # Test the container pushed in the previous step
  - name: "gcr.io/gcp-runtimes/container-structure-test"
    id: "containerTest"
    waitFor: ["getCredentials", "dockerLogin", "dockerBuildPush"]
    args:
      - 'test'
      - '--pull'
      - '--image'
      - 'harshavardhanj/binfmt:untested'
      - '--config'
      - './binfmt/container-structure-test.yaml'

  # Pull `docker-buildx:stable` image from Docker Hub and build 'binfmt' image with multi-arch support
  ### NOTE:
  ###     In the build step below, the `docker-buildx:stable` image is used to build
  ###     the `binfmt:testing` image with multi-arch support. Therefore, since
  ###     there is a cyclical dependency because the `docker-buildx:stable` image uses
  ###     the `binfmt:stable` image, before running this in Cloud Build, a working
  ###     version of the `docker-buildx:stable`, and of `binfmt:stable` image will need 
  ###     to be present in the container registry(Docker Hub, in this case). The image will
  ###     need to be built either locally or elsewhere and pushed to the registry before the 
  ###     below step can be run.
  - name: 'harshavardhanj/docker-buildx:stable'
    id: "dockerBuildxPush"
    waitFor: ["getCredentials", "dockerLogin", "dockerBuildPush", "containerTest"]
    entrypoint: 'sh'
    args:
      - '-c'
      - '/usr/bin/entrypoint.sh'
      - 'build'
      - '--build-arg'
      - 'BUILD_DATE=$(date --utc +%Y-%m-%dT%H:%M:%SZ)'
      - '--build-arg'
      - 'VCS_REF=$SHORT_SHA'
      - '-t'
      - 'harshavardhanj/binfmt:latest'
      - '-t'
      - 'harshavardhanj/binfmt:stable'
      - '--platform'
      - 'linux/amd64,linux/arm64,linux/ppc64le,linux/s390x,linux/386'
      - '--cache-from'
      - 'harshavardhanj/binfmt:latest'
      - '--pull'
      - '-f'
      - './binfmt/Dockerfile'
      - '--push'
      - './binfmt/.'
timeout: "3600s"
