# Docker Compose file for 'pwndrop'
#
version: "3.4"
services:
  pwndrop:
    image: harshavardhanj/pwndrop:latest
    restart: always
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./pwndrop-data:/usr/local/pwndrop/data
      - ./pwndrop.ini:/usr/local/pwndrop/pwndrop.ini
