version: "3.5"

services:

    openssh:
        image: harshavardhanj/openssh:jessie
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "2222:22"
       secrets:
           - ssh_user
           - ssh_password
           - ssh_pubkey
        environment:
            - USER_FILE=/run/secrets/ssh_user
            - PASSWORD_FILE=/run/secrets/ssh_password
            - SSH_PUBKEY=/run/secrets/ssh_pubkey
        deploy:
            mode: replicated
            replicas: 3
            placement:
                constraints:
                    - node.role == worker
            update_config:
                parallelism: 1
                delay: 10s
            restart_policy:
                condition: on-failure
                delay: 10s

secrets:
    ssh_user:
        file: ./ssh_user
    ssh_password:
        file: ./ssh_password
    ssh_pubkey:
        file: ./ssh_pubkey
